/**
 * Legacy demo catalog + firm letterhead only.
 * Generate Invoice no longer loads GENERATE_CLIENTS / GENERATE_MATTERS for the
 * workflow. Clients, matters, and time come from CounselFlow modules.
 * Keep FIRM_INFO for invoice preview letterhead until a firm settings source exists.
 */
import type {
  GenerateClient,
  GenerateMatter,
} from "@/lib/billing/generate-invoice-types";

export const FIRM_INFO = {
  name: "North & Vale LLP",
  address: "1200 LaSalle Street, Suite 2800, Chicago, IL 60602",
  phone: "(312) 555-0180",
  email: "billing@northandvale.law",
};

export const GENERATE_CLIENTS: GenerateClient[] = [
  {
    id: "gc-1",
    clientId: "CLT-10042",
    name: "Northline Capital",
    billingContact: "Jordan Miles, GC",
    billingMethod: "Hourly",
    trustRetainerBalance: 18500,
    email: "jmiles@northlinecap.com",
    phone: "(312) 555-0142",
    address: "200 W Madison St, Suite 3400, Chicago, IL 60606",
  },
  {
    id: "gc-2",
    clientId: "CLT-10088",
    name: "Harborview Medical",
    billingContact: "Dr. Alicia Cho, CLO",
    billingMethod: "Retainer",
    trustRetainerBalance: 42000,
    email: "acho@harborviewmed.org",
    phone: "(617) 555-0198",
    address: "88 Harbor Blvd, Boston, MA 02110",
  },
  {
    id: "gc-3",
    clientId: "CLT-10115",
    name: "Ridgecrest Properties",
    billingContact: "Marta Klein, VP Legal",
    billingMethod: "Fixed Fee",
    trustRetainerBalance: 7500,
    email: "mklein@ridgecrest.com",
    phone: "(404) 555-0114",
    address: "1200 Peachtree St NE, Atlanta, GA 30309",
  },
  {
    id: "gc-4",
    clientId: "CLT-10140",
    name: "Lumen Tech Holdings",
    billingContact: "Dev Patel, Head of Legal Ops",
    billingMethod: "Hourly",
    trustRetainerBalance: 9600,
    email: "dpatel@lumentech.io",
    phone: "(650) 555-0160",
    address: "3500 Deer Creek Rd, Palo Alto, CA 94304",
  },
  {
    id: "gc-5",
    clientId: "CL-1042",
    name: "Jordan Hale",
    billingContact: "Jordan Hale",
    billingMethod: "Fixed Fee",
    trustRetainerBalance: 12500,
    email: "jordan.hale@example.com",
    phone: "(512) 555-0142",
    address: "1842 West Oak St, Austin, TX 78701",
  },
];

export const GENERATE_MATTERS: GenerateMatter[] = [
  {
    id: "gm-1",
    clientId: "gc-1",
    matterName: "Series B Financing",
    matterNumber: "NV-M-22041",
    responsibleAttorney: "Elena Vargas",
    status: "Open",
    billingPeriod: "2026-07",
    timeEntries: [
      {
        id: "gt-1",
        date: "2026-07-08",
        person: "Elena Vargas",
        role: "Attorney",
        description:
          "SPA negotiation call with lead investor counsel regarding protective provisions, information rights, and board observer seats; coordinated markup package for partnership review.",
        hours: 2.5,
        rate: 650,
        approvalStatus: "Approved",
        billed: false,
      },
      {
        id: "gt-2",
        date: "2026-07-10",
        person: "Priya Shah",
        role: "Attorney",
        description:
          "Review of investor rights agreement redlines from co-counsel, including registration rights schedule, ROFR mechanics, and drag-along thresholds; circulated issue list to deal team.",
        hours: 4.0,
        rate: 520,
        approvalStatus: "Approved",
        billed: false,
      },
      {
        id: "gt-3",
        date: "2026-07-12",
        person: "Alex Chen",
        role: "Staff",
        description: "Closing checklist assembly and exhibit indexing",
        hours: 3.5,
        rate: 185,
        approvalStatus: "Approved",
        billed: false,
      },
      {
        id: "gt-4",
        date: "2026-07-09",
        person: "Jonah Reed",
        role: "Attorney",
        description:
          "Draft opinion letter outline (pending partner review) covering authority, enforceability, and capital stock due diligence assumptions.",
        hours: 1.5,
        rate: 410,
        approvalStatus: "Pending",
        billed: false,
      },
      {
        id: "gt-1r",
        date: "2026-07-11",
        person: "Sam Ortiz",
        role: "Staff",
        description:
          "Duplicate tabulation of investor signatories (rejected as non-billable administrative error and reassigned).",
        hours: 1.0,
        rate: 165,
        approvalStatus: "Rejected",
        billed: false,
      },
    ],
    expenses: [
      {
        id: "ge-1",
        date: "2026-07-09",
        category: "Legal Research Charges",
        description: "Westlaw research — financing precedents",
        amount: 285,
        approved: true,
        billed: false,
      },
      {
        id: "ge-2",
        date: "2026-07-11",
        category: "Postage",
        description: "Overnight courier — signature packets",
        amount: 64,
        approved: true,
        billed: false,
      },
      {
        id: "ge-3",
        date: "2026-07-08",
        category: "Copying",
        description: "Closing book production",
        amount: 120,
        approved: true,
        billed: false,
      },
    ],
    writeDowns: [
      {
        id: "gw-1",
        reason: "Junior onboarding time written off (approved)",
        amount: 400,
        approved: true,
      },
    ],
    courtesyDiscountApproved: 250,
  },
  {
    id: "gm-2",
    clientId: "gc-1",
    matterName: "M&A Diligence — Summit Co.",
    matterNumber: "NV-M-22058",
    responsibleAttorney: "Elena Vargas",
    status: "Open",
    billingPeriod: "2026-07",
    timeEntries: [
      {
        id: "gt-5",
        date: "2026-07-14",
        person: "Elena Vargas",
        role: "Attorney",
        description: "Data room prioritization with client deal team",
        hours: 1.8,
        rate: 650,
        approvalStatus: "Approved",
        billed: false,
      },
      {
        id: "gt-6",
        date: "2026-07-16",
        person: "Marcus Hale",
        role: "Attorney",
        description:
          "Material contracts review — wave 1: customer MSAs over $250k TCV, change-of-control provisions, and assignment restrictions flagged for disclosed schedule preparation.",
        hours: 6.0,
        rate: 575,
        approvalStatus: "Approved",
        billed: false,
      },
      {
        id: "gt-6p",
        date: "2026-07-17",
        person: "Priya Shah",
        role: "Attorney",
        description:
          "IP chain-of-title memo draft awaiting supervising attorney sign-off before billing approval.",
        hours: 2.0,
        rate: 520,
        approvalStatus: "Pending",
        billed: false,
      },
    ],
    expenses: [
      {
        id: "ge-4",
        date: "2026-07-15",
        category: "Legal Research Charges",
        description: "Deal diligence database access",
        amount: 190,
        approved: true,
        billed: false,
      },
    ],
    writeDowns: [],
    courtesyDiscountApproved: 0,
  },
  {
    id: "gm-3",
    clientId: "gc-2",
    matterName: "Employment Compliance Review",
    matterNumber: "NV-M-21990",
    responsibleAttorney: "Marcus Hale",
    status: "Open",
    billingPeriod: "2026-06",
    timeEntries: [
      {
        id: "gt-7",
        date: "2026-06-18",
        person: "Marcus Hale",
        role: "Attorney",
        description: "Handbook audit kickoff with HR leadership",
        hours: 2.0,
        rate: 575,
        approvalStatus: "Approved",
        billed: false,
      },
      {
        id: "gt-8",
        date: "2026-06-20",
        person: "Camille Ortiz",
        role: "Attorney",
        description:
          "Multi-state wage policy matrix covering CA, MA, NY, TX, and FL overtime, meal-period, and exempt classification rules; mapped handbook sections requiring client redlines.",
        hours: 5.5,
        rate: 490,
        approvalStatus: "Approved",
        billed: false,
      },
      {
        id: "gt-9",
        date: "2026-06-22",
        person: "Sam Ortiz",
        role: "Staff",
        description: "Policy appendix formatting and version control",
        hours: 2.2,
        rate: 165,
        approvalStatus: "Approved",
        billed: false,
      },
      {
        id: "gt-9r",
        date: "2026-06-21",
        person: "Sam Ortiz",
        role: "Staff",
        description:
          "Internal training attendance recorded in error against matter (rejected; not client-billable).",
        hours: 1.5,
        rate: 165,
        approvalStatus: "Rejected",
        billed: false,
      },
    ],
    expenses: [
      {
        id: "ge-5",
        date: "2026-06-19",
        category: "Travel",
        description: "Train to Boston — client onsite session",
        amount: 210,
        approved: true,
        billed: false,
      },
      {
        id: "ge-6",
        date: "2026-06-21",
        category: "Copying",
        description: "Handbook bound handouts",
        amount: 88,
        approved: true,
        billed: false,
      },
    ],
    writeDowns: [
      {
        id: "gw-2",
        reason: "Client courtesy on fixed-scope overage",
        amount: 750,
        approved: true,
      },
    ],
    courtesyDiscountApproved: 500,
  },
  {
    id: "gm-4",
    clientId: "gc-3",
    matterName: "Commercial Lease Portfolio",
    matterNumber: "NV-M-21810",
    responsibleAttorney: "Jonah Reed",
    status: "Open",
    billingPeriod: "2026-07",
    timeEntries: [
      {
        id: "gt-10",
        date: "2026-07-02",
        person: "Jonah Reed",
        role: "Attorney",
        description: "Lease abstraction — retail strip centers B/C",
        hours: 4.5,
        rate: 410,
        approvalStatus: "Approved",
        billed: false,
      },
      {
        id: "gt-11",
        date: "2026-07-05",
        person: "Elena Vargas",
        role: "Attorney",
        description: "Default notice strategy call",
        hours: 1.2,
        rate: 650,
        approvalStatus: "Approved",
        billed: false,
      },
    ],
    expenses: [
      {
        id: "ge-7",
        date: "2026-07-03",
        category: "Court Filing Fees",
        description: "County recorder fees — estoppel package",
        amount: 175,
        approved: true,
        billed: false,
      },
      {
        id: "ge-8",
        date: "2026-07-04",
        category: "Expert Witness Fees",
        description: "Construction cost consultant deposit",
        amount: 1500,
        approved: true,
        billed: false,
      },
    ],
    writeDowns: [],
    courtesyDiscountApproved: 0,
  },
  {
    id: "gm-5",
    clientId: "gc-4",
    matterName: "Export Controls Review",
    matterNumber: "NV-M-22102",
    responsibleAttorney: "Camille Ortiz",
    status: "Open",
    billingPeriod: "2026-07",
    timeEntries: [
      {
        id: "gt-12",
        date: "2026-07-07",
        person: "Camille Ortiz",
        role: "Attorney",
        description:
          "EAR classification conference with trade specialist reviewing ECCN candidates for product family LTH-200; documented commodity jurisdiction questions for follow-up filings.",
        hours: 3.0,
        rate: 490,
        approvalStatus: "Approved",
        billed: false,
      },
      {
        id: "gt-12p",
        date: "2026-07-09",
        person: "Priya Shah",
        role: "Attorney",
        description:
          "Draft license exception memo — pending compliance partner approval.",
        hours: 1.8,
        rate: 520,
        approvalStatus: "Pending",
        billed: false,
      },
    ],
    expenses: [
      {
        id: "ge-9",
        date: "2026-07-08",
        category: "Expert Witness Fees",
        description: "Outside trade counsel pass-through",
        amount: 2400,
        approved: true,
        billed: false,
      },
      {
        id: "ge-10",
        date: "2026-07-08",
        category: "Legal Research Charges",
        description: "Export classification database",
        amount: 320,
        approved: true,
        billed: false,
      },
    ],
    writeDowns: [],
    courtesyDiscountApproved: 100,
  },
  {
    id: "gm-6",
    clientId: "gc-2",
    matterName: "Physician Network Joint Venture (closed)",
    matterNumber: "NV-M-21755",
    responsibleAttorney: "Marcus Hale",
    status: "Closed",
    billingPeriod: "2026-05",
    timeEntries: [
      {
        id: "gt-13",
        date: "2026-05-04",
        person: "Marcus Hale",
        role: "Attorney",
        description: "Final governance grid delivery",
        hours: 2.0,
        rate: 575,
        approvalStatus: "Approved",
        billed: true,
      },
    ],
    expenses: [],
    writeDowns: [],
    courtesyDiscountApproved: 0,
  },
  {
    id: "gm-hale-1",
    clientId: "gc-5",
    matterName: "State v. Hale — Traffic Citation",
    matterNumber: "2026-0142",
    responsibleAttorney: "Avery Counsel",
    status: "Open",
    billingPeriod: "2026-08",
    timeEntries: [
      {
        id: "gt-hale-1",
        date: "2026-08-01",
        person: "Avery Counsel",
        role: "Attorney",
        description: "Case strategy conference and court preparation",
        hours: 2.0,
        rate: 500,
        approvalStatus: "Approved",
        billed: false,
      },
      {
        id: "gt-hale-2",
        date: "2026-08-03",
        person: "Parker Legal",
        role: "Staff",
        description: "Assemble citation packet and client correspondence",
        hours: 1.5,
        rate: 125,
        approvalStatus: "Approved",
        billed: false,
      },
    ],
    expenses: [
      {
        id: "ge-hale-1",
        date: "2026-08-02",
        category: "Filing fees",
        description: "Traffic court filing fee",
        amount: 85,
        approved: true,
        billed: false,
      },
    ],
    writeDowns: [],
    courtesyDiscountApproved: 0,
  },
  {
    id: "gm-hale-2",
    clientId: "gc-5",
    matterName: "Hale Estate Planning Package",
    matterNumber: "2026-0188",
    responsibleAttorney: "Avery Counsel",
    status: "Open",
    billingPeriod: "2026-08",
    timeEntries: [
      {
        id: "gt-hale-3",
        date: "2026-08-04",
        person: "Avery Counsel",
        role: "Attorney",
        description: "Draft will and powers of attorney revisions",
        hours: 3.0,
        rate: 500,
        approvalStatus: "Approved",
        billed: false,
      },
    ],
    expenses: [],
    writeDowns: [],
    courtesyDiscountApproved: 0,
  },
];

export function getMattersForClient(clientId: string): GenerateMatter[] {
  return GENERATE_MATTERS.filter((m) => m.clientId === clientId);
}

/**
 * Sequential invoice numbers in creation order.
 * 1st invoice → NV-2026-1101, 2nd → NV-2026-1102, etc.
 * @param existingCount invoices already created (by date created order)
 */
export function nextInvoiceNumber(existingCount: number): string {
  const seq = 1101 + Math.max(0, existingCount);
  return `NV-2026-${String(seq).padStart(4, "0")}`;
}
