import type { Invoice } from "@/lib/billing/invoice-types";

/**
 * Realistic law-firm seed data for Invoice Management demos.
 * Spans multiple years; dashboard period filters slice by invoice / payment dates.
 * Not connected to Supabase yet — swap for live queries later.
 */
export const CORE_INVOICE_SEED: Invoice[] = [
  {
    id: "inv-1001",
    invoiceNumber: "NV-2026-1001",
    client: "Northline Capital",
    legalMatter: "Series B Financing",
    attorney: "Elena Vargas",
    billingMethod: "Hourly",
    invoiceDate: "2026-07-02",
    dueDate: "2026-08-01",
    totalAmount: 28400,
    amountPaid: 14200,
    remainingBalance: 14200,
    status: "Partially Paid",
    clientInfo: {
      name: "Northline Capital",
      contact: "Jordan Miles, GC",
      email: "jmiles@northlinecap.com",
      phone: "(312) 555-0142",
      billingAddress: "200 W Madison St, Suite 3400, Chicago, IL 60606",
    },
    matterDescription:
      "Lead counsel on preferred equity Series B round, investor docs, and side letter negotiations.",
    timeEntries: [
      {
        id: "te-1",
        date: "2026-06-18",
        attorney: "Elena Vargas",
        description: "SPA markup and investor call",
        hours: 4.5,
        rate: 650,
        amount: 2925,
      },
      {
        id: "te-2",
        date: "2026-06-22",
        attorney: "Priya Shah",
        description: "Due diligence memo — IP schedule",
        hours: 6.2,
        rate: 520,
        amount: 3224,
      },
      {
        id: "te-3",
        date: "2026-06-28",
        attorney: "Elena Vargas",
        description: "Closing checklist and fund flow review",
        hours: 5.0,
        rate: 650,
        amount: 3250,
      },
    ],
    reimbursableExpenses: [
      {
        id: "ex-1",
        date: "2026-06-20",
        description: "Corporate filing — Illinois SOS",
        amount: 175,
      },
      {
        id: "ex-2",
        date: "2026-06-25",
        description: "Overnight courier — investor packs",
        amount: 86,
      },
    ],
    writeDowns: [
      {
        id: "wd-1",
        date: "2026-06-30",
        reason: "Junior associate orientation time written off",
        amount: 900,
      },
    ],
    retainerApplied: 5000,
    paymentHistory: [
      {
        id: "pay-1",
        date: "2026-07-15",
        method: "ACH",
        reference: "ACH-77821",
        amount: 14200,
      },
    ],
  },
  {
    id: "inv-1002",
    invoiceNumber: "NV-2026-1002",
    client: "Harborview Medical",
    legalMatter: "Employment Compliance Review",
    attorney: "Marcus Hale",
    billingMethod: "Fixed Fee",
    invoiceDate: "2026-06-28",
    dueDate: "2026-07-28",
    totalAmount: 19650,
    amountPaid: 0,
    remainingBalance: 19650,
    status: "Overdue",
    clientInfo: {
      name: "Harborview Medical",
      contact: "Dr. Alicia Cho, CLO",
      email: "acho@harborviewmed.org",
      phone: "(617) 555-0198",
      billingAddress: "88 Harbor Blvd, Boston, MA 02110",
    },
    matterDescription:
      "Fixed-fee review of handbooks, non-competes, and multi-state wage policies.",
    timeEntries: [
      {
        id: "te-4",
        date: "2026-06-10",
        attorney: "Marcus Hale",
        description: "Policy gap analysis kickoff",
        hours: 3.0,
        rate: 0,
        amount: 0,
      },
      {
        id: "te-5",
        date: "2026-06-14",
        attorney: "Camille Ortiz",
        description: "Handbook redline package",
        hours: 8.5,
        rate: 0,
        amount: 0,
      },
    ],
    reimbursableExpenses: [
      {
        id: "ex-3",
        date: "2026-06-16",
        description: "Research database (month prorata)",
        amount: 250,
      },
    ],
    writeDowns: [],
    retainerApplied: 0,
    paymentHistory: [],
    lastReminderSent: "2026-07-30",
    reminderCount: 1,
    reminderStatus: "Reminder Sent",
  },
  {
    id: "inv-1003",
    invoiceNumber: "NV-2026-1003",
    client: "Alder & Finch LLP",
    legalMatter: "Outside Counsel Fee Dispute",
    attorney: "Priya Shah",
    billingMethod: "Hourly",
    invoiceDate: "2026-07-10",
    dueDate: "2026-08-09",
    totalAmount: 8750,
    amountPaid: 0,
    remainingBalance: 8750,
    status: "Sent",
    clientInfo: {
      name: "Alder & Finch LLP",
      contact: "Sam Richter, Managing Partner",
      email: "srichter@alderfinch.law",
      phone: "(212) 555-0177",
      billingAddress: "450 Park Ave, 22nd Floor, New York, NY 10022",
    },
    matterDescription:
      "Arbitration counsel regarding disputed third-party litigation vendor fees.",
    timeEntries: [
      {
        id: "te-6",
        date: "2026-07-01",
        attorney: "Priya Shah",
        description: "Demand letter and exhibits",
        hours: 4.0,
        rate: 520,
        amount: 2080,
      },
      {
        id: "te-7",
        date: "2026-07-06",
        attorney: "Jonah Reed",
        description: "Invoice forensic summary",
        hours: 5.5,
        rate: 410,
        amount: 2255,
      },
    ],
    reimbursableExpenses: [],
    writeDowns: [],
    retainerApplied: 0,
    paymentHistory: [],
  },
  {
    id: "inv-1004",
    invoiceNumber: "NV-2026-1004",
    client: "Ridgecrest Properties",
    legalMatter: "Commercial Lease Portfolio",
    attorney: "Jonah Reed",
    billingMethod: "Retainer",
    invoiceDate: "2026-05-15",
    dueDate: "2026-06-14",
    totalAmount: 42100,
    amountPaid: 17300,
    remainingBalance: 24800,
    status: "Overdue",
    clientInfo: {
      name: "Ridgecrest Properties",
      contact: "Marta Klein, VP Legal",
      email: "mklein@ridgecrest.com",
      phone: "(404) 555-0114",
      billingAddress: "1200 Peachtree St NE, Atlanta, GA 30309",
    },
    matterDescription:
      "Retainer-backed portfolio work on nine retail leases and landlord notices.",
    timeEntries: [
      {
        id: "te-8",
        date: "2026-05-02",
        attorney: "Jonah Reed",
        description: "Lease abstraction — strip centers B/C",
        hours: 7.0,
        rate: 410,
        amount: 2870,
      },
      {
        id: "te-9",
        date: "2026-05-08",
        attorney: "Elena Vargas",
        description: "Default notice strategy call",
        hours: 1.5,
        rate: 650,
        amount: 975,
      },
    ],
    reimbursableExpenses: [
      {
        id: "ex-4",
        date: "2026-05-09",
        description: "Title search batch — Fulton County",
        amount: 640,
      },
    ],
    writeDowns: [
      {
        id: "wd-2",
        date: "2026-05-12",
        reason: "Client goodwill credit on form abstracts",
        amount: 1200,
      },
    ],
    retainerApplied: 15000,
    paymentHistory: [
      {
        id: "pay-2",
        date: "2026-05-20",
        method: "Wire",
        reference: "WIR-44109",
        amount: 17300,
      },
    ],
    lastReminderSent: "2026-07-05",
    reminderCount: 3,
    reminderStatus: "Reminder Sent",
  },
  {
    id: "inv-1005",
    invoiceNumber: "NV-2026-1005",
    client: "Lumen Tech Holdings",
    legalMatter: "IP Assignment Agreements",
    attorney: "Camille Ortiz",
    billingMethod: "Fixed Fee",
    invoiceDate: "2026-07-18",
    dueDate: "2026-08-17",
    totalAmount: 15300,
    amountPaid: 15300,
    remainingBalance: 0,
    status: "Paid",
    clientInfo: {
      name: "Lumen Tech Holdings",
      contact: "Dev Patel, Head of Legal Ops",
      email: "dpatel@lumentech.io",
      phone: "(650) 555-0160",
      billingAddress: "3500 Deer Creek Rd, Palo Alto, CA 94304",
    },
    matterDescription:
      "Fixed-fee package for inventor assignments and contractor IP transfers.",
    timeEntries: [
      {
        id: "te-10",
        date: "2026-07-08",
        attorney: "Camille Ortiz",
        description: "Assignment form suite + schedules",
        hours: 6.0,
        rate: 0,
        amount: 0,
      },
    ],
    reimbursableExpenses: [],
    writeDowns: [],
    retainerApplied: 0,
    paymentHistory: [
      {
        id: "pay-3",
        date: "2026-07-25",
        method: "Credit card",
        reference: "CC-90211",
        amount: 15300,
      },
    ],
  },
  {
    id: "inv-1006",
    invoiceNumber: "NV-2026-1006",
    client: "Coastal Transit Co.",
    legalMatter: "Regulatory Defense",
    attorney: "Elena Vargas",
    billingMethod: "Hourly",
    invoiceDate: "2026-06-05",
    dueDate: "2026-07-05",
    totalAmount: 36750,
    amountPaid: 21450,
    remainingBalance: 15300,
    status: "Partially Paid",
    clientInfo: {
      name: "Coastal Transit Co.",
      contact: "Nina Brooks, Deputy GC",
      email: "nbrooks@coastaltransit.com",
      phone: "(503) 555-0133",
      billingAddress: "900 SW 5th Ave, Portland, OR 97204",
    },
    matterDescription:
      "Administrative defense of FTA operational findings and corrective plan.",
    timeEntries: [
      {
        id: "te-11",
        date: "2026-05-20",
        attorney: "Elena Vargas",
        description: "Agency conference prep",
        hours: 5.5,
        rate: 650,
        amount: 3575,
      },
      {
        id: "te-12",
        date: "2026-05-27",
        attorney: "Marcus Hale",
        description: "Witness outline and document log",
        hours: 9.0,
        rate: 575,
        amount: 5175,
      },
    ],
    reimbursableExpenses: [
      {
        id: "ex-5",
        date: "2026-05-28",
        description: "Travel — D.C. agency hearing",
        amount: 1280,
      },
    ],
    writeDowns: [],
    retainerApplied: 7500,
    paymentHistory: [
      {
        id: "pay-4",
        date: "2026-06-18",
        method: "ACH",
        reference: "ACH-66012",
        amount: 21450,
      },
    ],
  },
  {
    id: "inv-1007",
    invoiceNumber: "NV-2026-1007",
    client: "Northline Capital",
    legalMatter: "M&A Diligence — Summit Co.",
    attorney: "Elena Vargas",
    billingMethod: "Hourly",
    invoiceDate: "2026-07-22",
    dueDate: "2026-08-21",
    totalAmount: 51200,
    amountPaid: 0,
    remainingBalance: 51200,
    status: "Sent",
    clientInfo: {
      name: "Northline Capital",
      contact: "Jordan Miles, GC",
      email: "jmiles@northlinecap.com",
      phone: "(312) 555-0142",
      billingAddress: "200 W Madison St, Suite 3400, Chicago, IL 60606",
    },
    matterDescription:
      "Buy-side diligence for Summit Co. acquisition, contracts, and employment.",
    timeEntries: [
      {
        id: "te-13",
        date: "2026-07-12",
        attorney: "Elena Vargas",
        description: "Data room prioritization call",
        hours: 2.0,
        rate: 650,
        amount: 1300,
      },
      {
        id: "te-14",
        date: "2026-07-15",
        attorney: "Priya Shah",
        description: "Material contracts review (wave 1)",
        hours: 11.0,
        rate: 520,
        amount: 5720,
      },
    ],
    reimbursableExpenses: [
      {
        id: "ex-6",
        date: "2026-07-16",
        description: "Virtual data room administrative fee",
        amount: 400,
      },
    ],
    writeDowns: [],
    retainerApplied: 10000,
    paymentHistory: [],
  },
  {
    id: "inv-1008",
    invoiceNumber: "NV-2026-1008",
    client: "Harborview Medical",
    legalMatter: "Physician Network Joint Venture",
    attorney: "Marcus Hale",
    billingMethod: "Retainer",
    invoiceDate: "2026-04-12",
    dueDate: "2026-05-12",
    totalAmount: 67800,
    amountPaid: 67800,
    remainingBalance: 0,
    status: "Paid",
    clientInfo: {
      name: "Harborview Medical",
      contact: "Dr. Alicia Cho, CLO",
      email: "acho@harborviewmed.org",
      phone: "(617) 555-0198",
      billingAddress: "88 Harbor Blvd, Boston, MA 02110",
    },
    matterDescription:
      "JV formation docs, governance grid, and Stark analysis for physician network.",
    timeEntries: [
      {
        id: "te-15",
        date: "2026-03-28",
        attorney: "Marcus Hale",
        description: "Operating agreement draft v2",
        hours: 8.0,
        rate: 575,
        amount: 4600,
      },
    ],
    reimbursableExpenses: [],
    writeDowns: [],
    retainerApplied: 25000,
    paymentHistory: [
      {
        id: "pay-5",
        date: "2026-04-20",
        method: "Wire",
        reference: "WIR-55001",
        amount: 40000,
      },
      {
        id: "pay-6",
        date: "2026-05-02",
        method: "Wire",
        reference: "WIR-55088",
        amount: 27800,
      },
    ],
  },
  {
    id: "inv-1009",
    invoiceNumber: "NV-2026-1009",
    client: "Alder & Finch LLP",
    legalMatter: "Ethics Advisory Retainer",
    attorney: "Priya Shah",
    billingMethod: "Retainer",
    invoiceDate: "2026-07-01",
    dueDate: "2026-07-31",
    totalAmount: 4500,
    amountPaid: 0,
    remainingBalance: 4500,
    status: "Disputed",
    clientInfo: {
      name: "Alder & Finch LLP",
      contact: "Sam Richter, Managing Partner",
      email: "srichter@alderfinch.law",
      phone: "(212) 555-0177",
      billingAddress: "450 Park Ave, 22nd Floor, New York, NY 10022",
    },
    matterDescription:
      "Standing ethics retainer for lateral conflicts and screening opinions.",
    timeEntries: [
      {
        id: "te-16",
        date: "2026-06-24",
        attorney: "Priya Shah",
        description: "Conflicts screening memo",
        hours: 2.5,
        rate: 520,
        amount: 1300,
      },
    ],
    reimbursableExpenses: [],
    writeDowns: [],
    retainerApplied: 2000,
    paymentHistory: [],
  },
  {
    id: "inv-1010",
    invoiceNumber: "NV-2026-1010",
    client: "Ridgecrest Properties",
    legalMatter: "Construction Litigation — Phase I",
    attorney: "Jonah Reed",
    billingMethod: "Hourly",
    invoiceDate: "2026-07-25",
    dueDate: "2026-08-24",
    totalAmount: 22300,
    amountPaid: 0,
    remainingBalance: 22300,
    status: "Draft",
    clientInfo: {
      name: "Ridgecrest Properties",
      contact: "Marta Klein, VP Legal",
      email: "mklein@ridgecrest.com",
      phone: "(404) 555-0114",
      billingAddress: "1200 Peachtree St NE, Atlanta, GA 30309",
    },
    matterDescription:
      "Plaintiff workup on delayed campus build-out; expert retention pending.",
    timeEntries: [
      {
        id: "te-17",
        date: "2026-07-18",
        attorney: "Jonah Reed",
        description: "Complaint outline and damage matrix",
        hours: 5.0,
        rate: 410,
        amount: 2050,
      },
    ],
    reimbursableExpenses: [
      {
        id: "ex-7",
        date: "2026-07-19",
        description: "Court reporter — site inspection",
        amount: 920,
      },
    ],
    writeDowns: [],
    retainerApplied: 0,
    paymentHistory: [],
  },
  {
    id: "inv-1011",
    invoiceNumber: "NV-2026-1011",
    client: "Lumen Tech Holdings",
    legalMatter: "Export Controls Review",
    attorney: "Camille Ortiz",
    billingMethod: "Reimbursable",
    invoiceDate: "2026-06-08",
    dueDate: "2026-07-08",
    totalAmount: 11400,
    amountPaid: 0,
    remainingBalance: 11400,
    status: "Overdue",
    clientInfo: {
      name: "Lumen Tech Holdings",
      contact: "Dev Patel, Head of Legal Ops",
      email: "dpatel@lumentech.io",
      phone: "(650) 555-0160",
      billingAddress: "3500 Deer Creek Rd, Palo Alto, CA 94304",
    },
    matterDescription:
      "Pass-through reimbursable specialist counsel on EAR classification.",
    timeEntries: [
      {
        id: "te-18",
        date: "2026-05-30",
        attorney: "Camille Ortiz",
        description: "Coordination with trade specialist",
        hours: 1.5,
        rate: 490,
        amount: 735,
      },
    ],
    reimbursableExpenses: [
      {
        id: "ex-8",
        date: "2026-06-01",
        description: "Outside trade counsel invoice (pass-through)",
        amount: 9800,
      },
      {
        id: "ex-9",
        date: "2026-06-02",
        description: "Classification database access",
        amount: 865,
      },
    ],
    writeDowns: [],
    retainerApplied: 0,
    paymentHistory: [],
    lastReminderSent: null,
    reminderCount: 0,
    reminderStatus: "None",
  },
  {
    id: "inv-1012",
    invoiceNumber: "NV-2026-1012",
    client: "Coastal Transit Co.",
    legalMatter: "Environmental Compliance Audit",
    attorney: "Marcus Hale",
    billingMethod: "Fixed Fee",
    invoiceDate: "2026-07-26",
    dueDate: "2026-08-25",
    totalAmount: 26900,
    amountPaid: 0,
    remainingBalance: 0,
    status: "Cancelled",
    clientInfo: {
      name: "Coastal Transit Co.",
      contact: "Nina Brooks, Deputy GC",
      email: "nbrooks@coastaltransit.com",
      phone: "(503) 555-0133",
      billingAddress: "900 SW 5th Ave, Portland, OR 97204",
    },
    matterDescription:
      "Fixed-fee Phase I ESA legal review — matter cancelled after facility sale.",
    timeEntries: [
      {
        id: "te-19",
        date: "2026-07-20",
        attorney: "Marcus Hale",
        description: "Scope confirmation (pre-cancel)",
        hours: 1.0,
        rate: 0,
        amount: 0,
      },
    ],
    reimbursableExpenses: [],
    writeDowns: [
      {
        id: "wd-3",
        date: "2026-07-27",
        reason: "Matter cancelled — billings zeroed",
        amount: 26900,
      },
    ],
    retainerApplied: 0,
    paymentHistory: [],
  },
];

/** Shared client contact blocks for historical multi-period seed rows */
const CLIENT_PROFILES = {
  "Northline Capital": {
    name: "Northline Capital",
    contact: "Jordan Miles, GC",
    email: "jmiles@northlinecap.com",
    phone: "(312) 555-0142",
    billingAddress: "200 W Madison St, Suite 3400, Chicago, IL 60606",
  },
  "Harborview Medical": {
    name: "Harborview Medical",
    contact: "Dr. Alicia Cho, CLO",
    email: "acho@harborviewmed.org",
    phone: "(617) 555-0198",
    billingAddress: "88 Harbor Blvd, Boston, MA 02110",
  },
  "Alder & Finch LLP": {
    name: "Alder & Finch LLP",
    contact: "Sam Richter, Managing Partner",
    email: "srichter@alderfinch.law",
    phone: "(212) 555-0177",
    billingAddress: "450 Park Ave, 22nd Floor, New York, NY 10022",
  },
  "Ridgecrest Properties": {
    name: "Ridgecrest Properties",
    contact: "Marta Klein, VP Legal",
    email: "mklein@ridgecrest.com",
    phone: "(404) 555-0114",
    billingAddress: "1200 Peachtree St NE, Atlanta, GA 30309",
  },
  "Lumen Tech Holdings": {
    name: "Lumen Tech Holdings",
    contact: "Dev Patel, Head of Legal Ops",
    email: "dpatel@lumentech.io",
    phone: "(650) 555-0160",
    billingAddress: "3500 Deer Creek Rd, Palo Alto, CA 94304",
  },
  "Coastal Transit Co.": {
    name: "Coastal Transit Co.",
    contact: "Nina Brooks, Deputy GC",
    email: "nbrooks@coastaltransit.com",
    phone: "(503) 555-0133",
    billingAddress: "900 SW 5th Ave, Portland, OR 97204",
  },
} as const;

type PeriodSeedRow = {
  id: string;
  invoiceNumber: string;
  client: keyof typeof CLIENT_PROFILES;
  legalMatter: string;
  attorney: string;
  billingMethod: Invoice["billingMethod"];
  invoiceDate: string;
  dueDate: string;
  totalAmount: number;
  amountPaid: number;
  status: Invoice["status"];
  matterDescription: string;
  payments?: { date: string; method: string; reference: string; amount: number }[];
  lastReminderSent?: string | null;
  reminderCount?: number;
  reminderStatus?: Invoice["reminderStatus"];
};

function buildPeriodSeedInvoice(row: PeriodSeedRow): Invoice {
  const remaining = Math.max(0, Math.round((row.totalAmount - row.amountPaid) * 100) / 100);
  const teId = `${row.id}-te`;
  return {
    id: row.id,
    invoiceNumber: row.invoiceNumber,
    client: row.client,
    legalMatter: row.legalMatter,
    attorney: row.attorney,
    billingMethod: row.billingMethod,
    invoiceDate: row.invoiceDate,
    dueDate: row.dueDate,
    totalAmount: row.totalAmount,
    amountPaid: row.amountPaid,
    remainingBalance: remaining,
    status: row.status,
    clientInfo: { ...CLIENT_PROFILES[row.client] },
    matterDescription: row.matterDescription,
    timeEntries: [
      {
        id: teId,
        date: row.invoiceDate,
        attorney: row.attorney,
        description: "Professional services for the billing period",
        hours: Math.max(1, Math.round((row.totalAmount / 550) * 10) / 10),
        rate: 550,
        amount: row.totalAmount,
      },
    ],
    reimbursableExpenses: [],
    writeDowns: [],
    retainerApplied: 0,
    paymentHistory: (row.payments ?? []).map((p, i) => ({
      id: `${row.id}-pay-${i + 1}`,
      ...p,
    })),
    lastReminderSent: row.lastReminderSent,
    reminderCount: row.reminderCount,
    reminderStatus: row.reminderStatus,
  };
}

/**
 * Additional seed invoices spanning 2024–2026 so period filters show real change.
 * Includes August 2026 activity for the default “This Month” view.
 */
const HISTORICAL_INVOICE_SEED: Invoice[] = (
  [
    // —— August 2026 (This Month default as of early Aug 2026) ——
    {
      id: "inv-2001",
      invoiceNumber: "NV-2026-2001",
      client: "Northline Capital",
      legalMatter: "Series C Term Sheet",
      attorney: "Elena Vargas",
      billingMethod: "Hourly",
      invoiceDate: "2026-08-01",
      dueDate: "2026-08-31",
      totalAmount: 32800,
      amountPaid: 16400,
      status: "Partially Paid",
      matterDescription: "August term-sheet negotiation and preference stack analysis.",
      payments: [
        {
          date: "2026-08-03",
          method: "ACH",
          reference: "ACH-88201",
          amount: 16400,
        },
      ],
    },
    {
      id: "inv-2002",
      invoiceNumber: "NV-2026-2002",
      client: "Harborview Medical",
      legalMatter: "Credentialing Policy Update",
      attorney: "Marcus Hale",
      billingMethod: "Fixed Fee",
      invoiceDate: "2026-08-02",
      dueDate: "2026-09-01",
      totalAmount: 14200,
      amountPaid: 0,
      status: "Sent",
      matterDescription: "Fixed-fee medical staff bylaws and credentialing update.",
    },
    {
      id: "inv-2003",
      invoiceNumber: "NV-2026-2003",
      client: "Lumen Tech Holdings",
      legalMatter: "SaaS MSA Refresh",
      attorney: "Camille Ortiz",
      billingMethod: "Hourly",
      invoiceDate: "2026-08-03",
      dueDate: "2026-09-02",
      totalAmount: 18650,
      amountPaid: 18650,
      status: "Paid",
      matterDescription: "Customer MSA and DPA refresh for enterprise renewals.",
      payments: [
        {
          date: "2026-08-04",
          method: "Wire",
          reference: "WIR-99102",
          amount: 18650,
        },
      ],
    },
    {
      id: "inv-2004",
      invoiceNumber: "NV-2026-2004",
      client: "Ridgecrest Properties",
      legalMatter: "Tenant Default Notices",
      attorney: "Jonah Reed",
      billingMethod: "Retainer",
      invoiceDate: "2026-08-01",
      dueDate: "2026-08-15",
      totalAmount: 9750,
      amountPaid: 0,
      status: "Overdue",
      matterDescription: "Portfolio default notices and cure period tracking.",
      lastReminderSent: "2026-08-03",
      reminderCount: 1,
      reminderStatus: "Reminder Sent",
    },
    {
      id: "inv-2005",
      invoiceNumber: "NV-2026-2005",
      client: "Coastal Transit Co.",
      legalMatter: "Vendor RFP Counsel",
      attorney: "Priya Shah",
      billingMethod: "Hourly",
      invoiceDate: "2026-08-04",
      dueDate: "2026-09-03",
      totalAmount: 21400,
      amountPaid: 0,
      status: "Sent",
      matterDescription: "Procurement counsel on rolling stock maintenance RFP.",
    },
    // —— July 2026 (Last Month / core seed complement) ——
    {
      id: "inv-2010",
      invoiceNumber: "NV-2026-2010",
      client: "Alder & Finch LLP",
      legalMatter: "Conflicts Opinion — July",
      attorney: "Priya Shah",
      billingMethod: "Retainer",
      invoiceDate: "2026-07-08",
      dueDate: "2026-08-07",
      totalAmount: 6200,
      amountPaid: 6200,
      status: "Paid",
      matterDescription: "Monthly ethics retainer draw for July.",
      payments: [
        {
          date: "2026-07-20",
          method: "ACH",
          reference: "ACH-77110",
          amount: 6200,
        },
      ],
    },
    {
      id: "inv-2011",
      invoiceNumber: "NV-2026-2011",
      client: "Coastal Transit Co.",
      legalMatter: "Labor Negotiation Support",
      attorney: "Marcus Hale",
      billingMethod: "Hourly",
      invoiceDate: "2026-07-14",
      dueDate: "2026-08-13",
      totalAmount: 24500,
      amountPaid: 12000,
      status: "Partially Paid",
      matterDescription: "Collective bargaining prep and management caucus.",
      payments: [
        {
          date: "2026-07-28",
          method: "Wire",
          reference: "WIR-77144",
          amount: 12000,
        },
      ],
    },
    // —— Q2 2026 (Last Quarter when asOf is Aug 2026) ——
    {
      id: "inv-2020",
      invoiceNumber: "NV-2026-2020",
      client: "Northline Capital",
      legalMatter: "Fund Formation — SPV IV",
      attorney: "Elena Vargas",
      billingMethod: "Hourly",
      invoiceDate: "2026-04-08",
      dueDate: "2026-05-08",
      totalAmount: 45200,
      amountPaid: 45200,
      status: "Paid",
      matterDescription: "SPV IV formation and LPA syndication package.",
      payments: [
        {
          date: "2026-04-30",
          method: "Wire",
          reference: "WIR-44081",
          amount: 45200,
        },
      ],
    },
    {
      id: "inv-2021",
      invoiceNumber: "NV-2026-2021",
      client: "Harborview Medical",
      legalMatter: "HIPAA Risk Assessment",
      attorney: "Marcus Hale",
      billingMethod: "Fixed Fee",
      invoiceDate: "2026-05-06",
      dueDate: "2026-06-05",
      totalAmount: 28900,
      amountPaid: 28900,
      status: "Paid",
      matterDescription: "Enterprise HIPAA risk assessment counsel.",
      payments: [
        {
          date: "2026-05-22",
          method: "ACH",
          reference: "ACH-55106",
          amount: 28900,
        },
      ],
    },
    {
      id: "inv-2022",
      invoiceNumber: "NV-2026-2022",
      client: "Lumen Tech Holdings",
      legalMatter: "Acquisition — Vertex Labs",
      attorney: "Camille Ortiz",
      billingMethod: "Hourly",
      invoiceDate: "2026-06-12",
      dueDate: "2026-07-12",
      totalAmount: 61200,
      amountPaid: 30000,
      status: "Partially Paid",
      matterDescription: "Buy-side counsel on Vertex Labs asset purchase.",
      payments: [
        {
          date: "2026-06-28",
          method: "Wire",
          reference: "WIR-66128",
          amount: 30000,
        },
      ],
    },
    {
      id: "inv-2023",
      invoiceNumber: "NV-2026-2023",
      client: "Ridgecrest Properties",
      legalMatter: "Zoning Appeal — Midtown",
      attorney: "Jonah Reed",
      billingMethod: "Hourly",
      invoiceDate: "2026-06-20",
      dueDate: "2026-07-20",
      totalAmount: 18750,
      amountPaid: 0,
      status: "Overdue",
      matterDescription: "Zoning board appeal briefing and oral argument prep.",
      lastReminderSent: "2026-07-25",
      reminderCount: 2,
      reminderStatus: "Reminder Sent",
    },
    // —— Early 2026 (YTD remaining months) ——
    {
      id: "inv-2030",
      invoiceNumber: "NV-2026-2030",
      client: "Alder & Finch LLP",
      legalMatter: "Lateral Hire Screening",
      attorney: "Priya Shah",
      billingMethod: "Fixed Fee",
      invoiceDate: "2026-01-15",
      dueDate: "2026-02-14",
      totalAmount: 8500,
      amountPaid: 8500,
      status: "Paid",
      matterDescription: "Q1 lateral conflicts package for three partners.",
      payments: [
        {
          date: "2026-01-28",
          method: "ACH",
          reference: "ACH-16015",
          amount: 8500,
        },
      ],
    },
    {
      id: "inv-2031",
      invoiceNumber: "NV-2026-2031",
      client: "Coastal Transit Co.",
      legalMatter: "Bond Offering Diligence",
      attorney: "Elena Vargas",
      billingMethod: "Hourly",
      invoiceDate: "2026-02-10",
      dueDate: "2026-03-12",
      totalAmount: 39400,
      amountPaid: 39400,
      status: "Paid",
      matterDescription: "Disclosure counsel support for spring fare-box bonds.",
      payments: [
        {
          date: "2026-02-28",
          method: "Wire",
          reference: "WIR-26110",
          amount: 39400,
        },
      ],
    },
    {
      id: "inv-2032",
      invoiceNumber: "NV-2026-2032",
      client: "Northline Capital",
      legalMatter: "Portfolio Monitoring — Q1",
      attorney: "Elena Vargas",
      billingMethod: "Retainer",
      invoiceDate: "2026-03-05",
      dueDate: "2026-04-04",
      totalAmount: 22000,
      amountPaid: 22000,
      status: "Paid",
      matterDescription: "Quarterly portfolio company board materials review.",
      payments: [
        {
          date: "2026-03-18",
          method: "ACH",
          reference: "ACH-36105",
          amount: 22000,
        },
      ],
    },
    // —— 2025 ——
    {
      id: "inv-2101",
      invoiceNumber: "NV-2025-1188",
      client: "Harborview Medical",
      legalMatter: "Cyber Incident Response",
      attorney: "Marcus Hale",
      billingMethod: "Hourly",
      invoiceDate: "2025-11-12",
      dueDate: "2025-12-12",
      totalAmount: 54700,
      amountPaid: 54700,
      status: "Paid",
      matterDescription: "Incident response counsel and regulator notice package.",
      payments: [
        {
          date: "2025-11-30",
          method: "Wire",
          reference: "WIR-251112",
          amount: 30000,
        },
        {
          date: "2025-12-08",
          method: "Wire",
          reference: "WIR-251208",
          amount: 24700,
        },
      ],
    },
    {
      id: "inv-2102",
      invoiceNumber: "NV-2025-1204",
      client: "Lumen Tech Holdings",
      legalMatter: "Year-End Equity Refresh",
      attorney: "Camille Ortiz",
      billingMethod: "Fixed Fee",
      invoiceDate: "2025-12-05",
      dueDate: "2026-01-04",
      totalAmount: 16800,
      amountPaid: 16800,
      status: "Paid",
      matterDescription: "Option pool and RSU plan amendments for 2026 grants.",
      payments: [
        {
          date: "2025-12-20",
          method: "Credit card",
          reference: "CC-251220",
          amount: 16800,
        },
      ],
    },
    {
      id: "inv-2103",
      invoiceNumber: "NV-2025-1095",
      client: "Ridgecrest Properties",
      legalMatter: "Portfolio Refinancing",
      attorney: "Jonah Reed",
      billingMethod: "Hourly",
      invoiceDate: "2025-09-18",
      dueDate: "2025-10-18",
      totalAmount: 41200,
      amountPaid: 41200,
      status: "Paid",
      matterDescription: "Lender negotiations on multi-property refinance.",
      payments: [
        {
          date: "2025-10-02",
          method: "Wire",
          reference: "WIR-250918",
          amount: 41200,
        },
      ],
    },
    {
      id: "inv-2104",
      invoiceNumber: "NV-2025-1042",
      client: "Northline Capital",
      legalMatter: "Secondary Sale — Blue Harbor",
      attorney: "Elena Vargas",
      billingMethod: "Hourly",
      invoiceDate: "2025-06-24",
      dueDate: "2025-07-24",
      totalAmount: 36500,
      amountPaid: 36500,
      status: "Paid",
      matterDescription: "Secondary share transfer documentation and opinions.",
      payments: [
        {
          date: "2025-07-08",
          method: "ACH",
          reference: "ACH-250624",
          amount: 36500,
        },
      ],
    },
    {
      id: "inv-2105",
      invoiceNumber: "NV-2025-1018",
      client: "Coastal Transit Co.",
      legalMatter: "ADA Access Settlement",
      attorney: "Priya Shah",
      billingMethod: "Hourly",
      invoiceDate: "2025-03-11",
      dueDate: "2025-04-10",
      totalAmount: 27800,
      amountPaid: 27800,
      status: "Paid",
      matterDescription: "Consent decree negotiation on fleet accessibility.",
      payments: [
        {
          date: "2025-03-28",
          method: "Wire",
          reference: "WIR-250311",
          amount: 27800,
        },
      ],
    },
    // —— 2024 ——
    {
      id: "inv-2201",
      invoiceNumber: "NV-2024-0988",
      client: "Alder & Finch LLP",
      legalMatter: "Outside Counsel Audit Response",
      attorney: "Priya Shah",
      billingMethod: "Hourly",
      invoiceDate: "2024-11-06",
      dueDate: "2024-12-06",
      totalAmount: 19200,
      amountPaid: 19200,
      status: "Paid",
      matterDescription: "Historical fee audit production and narrative response.",
      payments: [
        {
          date: "2024-11-22",
          method: "ACH",
          reference: "ACH-241106",
          amount: 19200,
        },
      ],
    },
    {
      id: "inv-2202",
      invoiceNumber: "NV-2024-0944",
      client: "Harborview Medical",
      legalMatter: "GPO Contracting Round",
      attorney: "Marcus Hale",
      billingMethod: "Fixed Fee",
      invoiceDate: "2024-08-14",
      dueDate: "2024-09-13",
      totalAmount: 22500,
      amountPaid: 22500,
      status: "Paid",
      matterDescription: "Group purchasing organization master agreement.",
      payments: [
        {
          date: "2024-08-30",
          method: "Wire",
          reference: "WIR-240814",
          amount: 22500,
        },
      ],
    },
    {
      id: "inv-2203",
      invoiceNumber: "NV-2024-0912",
      client: "Lumen Tech Holdings",
      legalMatter: "Series A Closing Set",
      attorney: "Camille Ortiz",
      billingMethod: "Hourly",
      invoiceDate: "2024-05-21",
      dueDate: "2024-06-20",
      totalAmount: 48800,
      amountPaid: 48800,
      status: "Paid",
      matterDescription: "Company counsel on Series A preferred financing.",
      payments: [
        {
          date: "2024-06-04",
          method: "Wire",
          reference: "WIR-240521",
          amount: 48800,
        },
      ],
    },
    {
      id: "inv-2204",
      invoiceNumber: "NV-2024-0875",
      client: "Northline Capital",
      legalMatter: "LP Advisory — Mid-year",
      attorney: "Elena Vargas",
      billingMethod: "Retainer",
      invoiceDate: "2024-06-03",
      dueDate: "2024-07-03",
      totalAmount: 15000,
      amountPaid: 15000,
      status: "Paid",
      matterDescription: "Limited partner advisory memorandum for Fund III.",
      payments: [
        {
          date: "2024-06-18",
          method: "ACH",
          reference: "ACH-240603",
          amount: 15000,
        },
      ],
    },
  ] satisfies PeriodSeedRow[]
).map(buildPeriodSeedInvoice);

/** Full seed catalog: original demo set + multi-year historical rows */
export const INVOICE_SEED: Invoice[] = [
  ...CORE_INVOICE_SEED,
  ...HISTORICAL_INVOICE_SEED,
];

export const BILLING_METHODS = [
  "Hourly",
  "Fixed Fee",
  "Retainer",
  "Reimbursable",
] as const;

export const INVOICE_STATUSES = [
  "Draft",
  "Sent",
  "Paid",
  "Partially Paid",
  "Overdue",
  "Disputed",
  "Cancelled",
] as const;

/** Prefer pass-through live catalog; empty default (never seed). */
export function getInvoiceAttorneys(invoices: Invoice[] = []): string[] {
  return Array.from(
    new Set(
      invoices
        .map((i) => i.attorney?.trim())
        .filter((name): name is string => Boolean(name)),
    ),
  ).sort();
}
