/**
 * TEMPORARY MOCK DATA — Staff/Admin Operations
 *
 * This file holds demo data for UI development only.
 * It will later be replaced by Supabase queries against existing firm tables
 * (e.g. profiles, matter_assignments) plus any admin-specific tables
 * approved by the team (approvals, etc.).
 *
 * Do not treat these IDs as production database keys.
 */

import {
  buildDashboardSummary,
  buildProductivityMetrics,
  buildWorkloadItems,
} from "@/lib/admin/calculations";
import { MOCK_JOB_APPLICATIONS } from "@/lib/admin/job-applications-data";
import type {
  AdminApproval,
  AdminAssignment,
  AdminAttorneyProfile,
  AdminEmployee,
  AdminMatter,
  AdminNavItem,
  AdminRolePermission,
  AdminUnassignedMatter,
  AdminVacation,
} from "@/lib/admin/types";

export { MOCK_JOB_APPLICATIONS } from "@/lib/admin/job-applications-data";

/** Fixed “today” so due-soon / overdue demos stay stable. */
export const ADMIN_REFERENCE_DATE = "2026-08-04";

export const ADMIN_NAV_ITEMS: AdminNavItem[] = [
  {
    key: "dashboard",
    label: "Manager Dashboard",
    href: "/admin",
    description: "Firm staffing overview and productivity signals",
  },
  {
    key: "attorneys",
    label: "Attorney Management",
    href: "/admin/attorneys",
    description: "Attorney profiles and practice focus",
  },
  {
    key: "employees",
    label: "Employee Profiles",
    href: "/admin/employees",
    description: "Internal employee directory",
  },
  {
    key: "matters",
    label: "Matters",
    href: "/admin/matters",
    description: "Matter status, engagements, and staffing coverage",
  },
  {
    key: "assignments",
    label: "Assignments",
    href: "/admin/assignments",
    description: "Matter and case staffing assignments",
  },
  {
    key: "approvals",
    label: "Approval Queue",
    href: "/admin/approvals",
    description: "Pending internal approvals",
  },
  {
    key: "workload",
    label: "Workload Board",
    href: "/admin/workload",
    description: "Capacity and internal workload",
  },
  {
    key: "roles",
    label: "Role Permissions",
    href: "/admin/roles",
    description: "Admin role capability matrix",
  },
];

/**
 * 12+ employees across roles and practice areas.
 * Includes: overloaded (>100%), near capacity (90–100%), approved leave,
 * inactive, and several available attorneys.
 *
 * assignedHours = planned load; actualHoursWorked = hours worked.
 * availableWorkHours = capacity denominator for utilization.
 */
export const MOCK_EMPLOYEES: AdminEmployee[] = [
  {
    id: "emp-001",
    firstName: "Jordan",
    lastName: "Hale",
    fullName: "Jordan Hale",
    email: "jordan.hale@counselflow.demo",
    phone: "312-555-0101",
    employeeNumber: "EMP-001",
    title: "Managing Partner",
    department: "Leadership",
    roleKey: "managing_partner",
    roleLabel: "Managing Partner",
    practiceArea: "Firm Management",
    status: "active",
    hireDate: "2014-03-01",
    barNumber: "IL-220114",
    internalHourlyCostRate: 175,
    standardBillableRate: 450,
    weeklyCapacityHours: 80,
    targetBillableHours: 80,
    managerId: null,
    availableWorkHours: 80,
    assignedHours: 48,
    actualHoursWorked: 52,
    isAttorney: true,
  },
  {
    id: "emp-002",
    firstName: "Alex",
    lastName: "Rivera",
    fullName: "Alex Rivera",
    email: "alex.rivera@counselflow.demo",
    phone: "312-555-0102",
    employeeNumber: "EMP-002",
    title: "Senior Attorney",
    department: "Litigation",
    roleKey: "attorney",
    roleLabel: "Attorney",
    practiceArea: "Litigation",
    status: "active",
    hireDate: "2018-06-15",
    barNumber: "IL-448291",
    internalHourlyCostRate: 95,
    standardBillableRate: 375,
    weeklyCapacityHours: 160,
    targetBillableHours: 160,
    managerId: "emp-001",
    availableWorkHours: 160,
    assignedHours: 176,
    actualHoursWorked: 168,
    isAttorney: true,
  },
  {
    id: "emp-003",
    firstName: "Sam",
    lastName: "Okonkwo",
    fullName: "Sam Okonkwo",
    email: "sam.okonkwo@counselflow.demo",
    phone: "312-555-0103",
    employeeNumber: "EMP-003",
    title: "Associate Attorney",
    department: "Corporate",
    roleKey: "attorney",
    roleLabel: "Attorney",
    practiceArea: "Corporate",
    status: "active",
    hireDate: "2021-09-07",
    barNumber: "IL-552018",
    internalHourlyCostRate: 75,
    standardBillableRate: 295,
    weeklyCapacityHours: 150,
    targetBillableHours: 150,
    managerId: "emp-001",
    availableWorkHours: 150,
    assignedHours: 142,
    actualHoursWorked: 138,
    isAttorney: true,
  },
  {
    id: "emp-004",
    firstName: "Riley",
    lastName: "Chen",
    fullName: "Riley Chen",
    email: "riley.chen@counselflow.demo",
    phone: "312-555-0104",
    employeeNumber: "EMP-004",
    title: "Paralegal",
    department: "Litigation",
    roleKey: "paralegal",
    roleLabel: "Paralegal",
    practiceArea: "Litigation",
    status: "active",
    hireDate: "2020-01-20",
    barNumber: "",
    internalHourlyCostRate: 45,
    standardBillableRate: 175,
    weeklyCapacityHours: 160,
    targetBillableHours: 0,
    managerId: "emp-002",
    availableWorkHours: 160,
    assignedHours: 120,
    actualHoursWorked: 118,
    isAttorney: false,
  },
  {
    id: "emp-005",
    firstName: "Casey",
    lastName: "Brooks",
    fullName: "Casey Brooks",
    email: "casey.brooks@counselflow.demo",
    phone: "312-555-0105",
    employeeNumber: "EMP-005",
    title: "Firm Administrator",
    department: "Administration",
    roleKey: "firm_administrator",
    roleLabel: "Firm Administrator",
    practiceArea: "Administration",
    status: "on_leave",
    hireDate: "2016-11-02",
    barNumber: "",
    internalHourlyCostRate: 55,
    standardBillableRate: 0,
    weeklyCapacityHours: 160,
    targetBillableHours: 0,
    managerId: "emp-001",
    availableWorkHours: 160,
    assignedHours: 0,
    actualHoursWorked: 0,
    isAttorney: false,
  },
  {
    id: "emp-006",
    firstName: "Morgan",
    lastName: "Ellis",
    fullName: "Morgan Ellis",
    email: "morgan.ellis@counselflow.demo",
    phone: "312-555-0106",
    employeeNumber: "EMP-006",
    title: "Of Counsel",
    department: "Real Estate",
    roleKey: "attorney",
    roleLabel: "Attorney",
    practiceArea: "Real Estate",
    status: "inactive",
    hireDate: "2012-04-18",
    barNumber: "IL-190442",
    internalHourlyCostRate: 110,
    standardBillableRate: 400,
    weeklyCapacityHours: 0,
    targetBillableHours: 0,
    managerId: "emp-001",
    availableWorkHours: 0,
    assignedHours: 0,
    actualHoursWorked: 0,
    isAttorney: true,
  },
  {
    id: "emp-007",
    firstName: "Taylor",
    lastName: "Nguyen",
    fullName: "Taylor Nguyen",
    email: "taylor.nguyen@counselflow.demo",
    phone: "312-555-0107",
    employeeNumber: "EMP-007",
    title: "Senior Associate",
    department: "Employment",
    roleKey: "attorney",
    roleLabel: "Attorney",
    practiceArea: "Employment",
    status: "active",
    hireDate: "2019-08-12",
    barNumber: "IL-661203",
    internalHourlyCostRate: 85,
    standardBillableRate: 325,
    weeklyCapacityHours: 160,
    targetBillableHours: 160,
    managerId: "emp-001",
    availableWorkHours: 160,
    assignedHours: 96,
    actualHoursWorked: 102,
    isAttorney: true,
  },
  {
    id: "emp-008",
    firstName: "Jamie",
    lastName: "Patel",
    fullName: "Jamie Patel",
    email: "jamie.patel@counselflow.demo",
    phone: "312-555-0108",
    employeeNumber: "EMP-008",
    title: "Associate Attorney",
    department: "IP",
    roleKey: "attorney",
    roleLabel: "Attorney",
    practiceArea: "Intellectual Property",
    status: "active",
    hireDate: "2022-02-28",
    barNumber: "IL-772514",
    internalHourlyCostRate: 70,
    standardBillableRate: 285,
    weeklyCapacityHours: 160,
    targetBillableHours: 160,
    managerId: "emp-001",
    availableWorkHours: 160,
    assignedHours: 88,
    actualHoursWorked: 90,
    isAttorney: true,
  },
  {
    id: "emp-009",
    firstName: "Avery",
    lastName: "Kim",
    fullName: "Avery Kim",
    email: "avery.kim@counselflow.demo",
    phone: "312-555-0109",
    employeeNumber: "EMP-009",
    title: "Billing Specialist",
    department: "Finance",
    roleKey: "billing_specialist",
    roleLabel: "Billing Specialist",
    practiceArea: "Administration",
    status: "active",
    hireDate: "2017-05-09",
    barNumber: "",
    internalHourlyCostRate: 50,
    standardBillableRate: 0,
    weeklyCapacityHours: 160,
    targetBillableHours: 0,
    managerId: "emp-005",
    availableWorkHours: 160,
    assignedHours: 140,
    actualHoursWorked: 136,
    isAttorney: false,
  },
  {
    id: "emp-010",
    firstName: "Quinn",
    lastName: "Morales",
    fullName: "Quinn Morales",
    email: "quinn.morales@counselflow.demo",
    phone: "312-555-0110",
    employeeNumber: "EMP-010",
    title: "Partner",
    department: "Litigation",
    roleKey: "attorney",
    roleLabel: "Attorney",
    practiceArea: "Litigation",
    status: "active",
    hireDate: "2010-01-11",
    barNumber: "IL-110998",
    internalHourlyCostRate: 150,
    standardBillableRate: 475,
    weeklyCapacityHours: 140,
    targetBillableHours: 140,
    managerId: "emp-001",
    availableWorkHours: 140,
    assignedHours: 70,
    actualHoursWorked: 74,
    isAttorney: true,
  },
  {
    id: "emp-011",
    firstName: "Drew",
    lastName: "Santos",
    fullName: "Drew Santos",
    email: "drew.santos@counselflow.demo",
    phone: "312-555-0111",
    employeeNumber: "EMP-011",
    title: "Associate Attorney",
    department: "Corporate",
    roleKey: "attorney",
    roleLabel: "Attorney",
    practiceArea: "Corporate",
    status: "active",
    hireDate: "2023-03-14",
    barNumber: "IL-883627",
    internalHourlyCostRate: 65,
    standardBillableRate: 275,
    weeklyCapacityHours: 160,
    targetBillableHours: 160,
    managerId: "emp-003",
    availableWorkHours: 160,
    assignedHours: 64,
    actualHoursWorked: 58,
    isAttorney: true,
  },
  {
    id: "emp-012",
    firstName: "Harper",
    lastName: "Diaz",
    fullName: "Harper Diaz",
    email: "harper.diaz@counselflow.demo",
    phone: "312-555-0112",
    employeeNumber: "EMP-012",
    title: "Paralegal",
    department: "Corporate",
    roleKey: "paralegal",
    roleLabel: "Paralegal",
    practiceArea: "Corporate",
    status: "active",
    hireDate: "2021-07-19",
    barNumber: "",
    internalHourlyCostRate: 42,
    standardBillableRate: 165,
    weeklyCapacityHours: 160,
    targetBillableHours: 0,
    managerId: "emp-003",
    availableWorkHours: 160,
    assignedHours: 110,
    actualHoursWorked: 108,
    isAttorney: false,
  },
  {
    id: "emp-013",
    firstName: "Reese",
    lastName: "Coleman",
    fullName: "Reese Coleman",
    email: "reese.coleman@counselflow.demo",
    phone: "312-555-0113",
    employeeNumber: "EMP-013",
    title: "Senior Attorney",
    department: "Trusts & Estates",
    roleKey: "attorney",
    roleLabel: "Attorney",
    practiceArea: "Trusts & Estates",
    status: "active",
    hireDate: "2015-10-05",
    barNumber: "IL-334871",
    internalHourlyCostRate: 100,
    standardBillableRate: 350,
    weeklyCapacityHours: 160,
    targetBillableHours: 160,
    managerId: "emp-001",
    availableWorkHours: 160,
    assignedHours: 104,
    actualHoursWorked: 99,
    isAttorney: true,
  }
];

export const MOCK_ATTORNEYS: AdminAttorneyProfile[] = MOCK_EMPLOYEES.filter(
  (e) => e.isAttorney,
).map((e, index) => ({
  id: `aty-${String(index + 1).padStart(3, "0")}`,
  employeeId: e.id,
  fullName: e.fullName,
  email: e.email,
  practiceFocus: e.practiceArea,
  barNumber: e.barNumber,
  billableTargetHours: e.targetBillableHours,
  currentOpenMatters: e.id === "emp-002" ? 8 : e.id === "emp-003" ? 5 : 3,
  status: e.status,
}));

/**
 * Role permission matrix for Staff/Admin Operations (Person 5).
 * roleKeys stay stable for employee roster mapping.
 * Labels align to: Firm Administrator, Partner, Attorney, Paralegal, Billing Clerk, Client.
 *
 * UI edits update local page state only. Server-side enforcement and Supabase
 * Row Level Security must be added during integration — this is not production ACL.
 */
export const MOCK_ROLE_PERMISSIONS: AdminRolePermission[] = [
  {
    id: "role-002",
    roleKey: "firm_administrator",
    roleLabel: "Firm Administrator",
    description:
      "Full internal access: manage employees, roles, assignments, approvals, and workloads.",
    canAccessAdminSection: true,
    canViewManagerDashboard: true,
    canViewEmployeeDirectory: true,
    canManageEmployees: true,
    canViewEmployeeProfiles: true,
    canViewInternalCostRates: true,
    canManageRoles: true,
    canAssignMatters: true,
    canReassignMatters: true,
    canViewWorkload: true,
    canApproveWork: true,
    canApproveTimeEntries: true,
    canApproveExpenses: true,
    canApproveVacation: true,
    canApproveWriteDowns: true,
    canAccessBilling: true,
    canAccessAccounting: true,
    canViewAuditLogs: true,
  },
  {
    id: "role-001",
    roleKey: "managing_partner",
    roleLabel: "Partner",
    description:
      "Manager dashboard, employee profiles, assign/reassign matters, all workloads, and approvals. Cannot change protected Firm Administrator permissions unless specifically authorized.",
    canAccessAdminSection: false,
    canViewManagerDashboard: true,
    canViewEmployeeDirectory: true,
    canManageEmployees: false,
    canViewEmployeeProfiles: true,
    canViewInternalCostRates: false,
    canManageRoles: false,
    canAssignMatters: true,
    canReassignMatters: true,
    canViewWorkload: true,
    canApproveWork: true,
    canApproveTimeEntries: true,
    canApproveExpenses: true,
    canApproveVacation: true,
    canApproveWriteDowns: true,
    canAccessBilling: false,
    canAccessAccounting: false,
    canViewAuditLogs: false,
  },
  {
    id: "role-003",
    roleKey: "attorney",
    roleLabel: "Attorney",
    description:
      "Can view own profile, assignments, workload, and submitted requests. Cannot manage employees or roles, view internal cost rates, or view all employee workloads.",
    canAccessAdminSection: false,
    canViewManagerDashboard: false,
    canViewEmployeeDirectory: false,
    canManageEmployees: false,
    canViewEmployeeProfiles: false,
    canViewInternalCostRates: false,
    canManageRoles: false,
    canAssignMatters: false,
    canReassignMatters: false,
    canViewWorkload: false,
    canApproveWork: false,
    canApproveTimeEntries: false,
    canApproveExpenses: false,
    canApproveVacation: false,
    canApproveWriteDowns: false,
    canAccessBilling: false,
    canAccessAccounting: false,
    canViewAuditLogs: false,
  },
  {
    id: "role-004",
    roleKey: "paralegal",
    roleLabel: "Paralegal",
    description:
      "Can view own profile, assignments, workload, and submitted requests. Cannot manage employees or roles, approve requests, or view internal cost rates.",
    canAccessAdminSection: false,
    canViewManagerDashboard: false,
    canViewEmployeeDirectory: false,
    canManageEmployees: false,
    canViewEmployeeProfiles: false,
    canViewInternalCostRates: false,
    canManageRoles: false,
    canAssignMatters: false,
    canReassignMatters: false,
    canViewWorkload: false,
    canApproveWork: false,
    canApproveTimeEntries: false,
    canApproveExpenses: false,
    canApproveVacation: false,
    canApproveWriteDowns: false,
    canAccessBilling: false,
    canAccessAccounting: false,
    canViewAuditLogs: false,
  },
  {
    id: "role-005",
    roleKey: "billing_specialist",
    roleLabel: "Billing Clerk",
    description:
      "Can view employee information needed for billing, access billing, and participate in billing-related approvals. Cannot manage roles, access the Admin/Staff section, or view unrestricted internal cost rates.",
    canAccessAdminSection: false,
    canViewManagerDashboard: false,
    canViewEmployeeDirectory: true,
    canManageEmployees: false,
    canViewEmployeeProfiles: true,
    canViewInternalCostRates: false,
    canManageRoles: false,
    canAssignMatters: false,
    canReassignMatters: false,
    canViewWorkload: false,
    canApproveWork: false,
    canApproveTimeEntries: true,
    canApproveExpenses: true,
    canApproveVacation: false,
    canApproveWriteDowns: false,
    canAccessBilling: true,
    canAccessAccounting: false,
    canViewAuditLogs: false,
  },
  {
    id: "role-006",
    roleKey: "client",
    roleLabel: "Client",
    description:
      "No Admin section access. Cannot view employees, internal workload, internal cost rates, assignments, or approval records.",
    canAccessAdminSection: false,
    canViewManagerDashboard: false,
    canViewEmployeeDirectory: false,
    canManageEmployees: false,
    canViewEmployeeProfiles: false,
    canViewInternalCostRates: false,
    canManageRoles: false,
    canAssignMatters: false,
    canReassignMatters: false,
    canViewWorkload: false,
    canApproveWork: false,
    canApproveTimeEntries: false,
    canApproveExpenses: false,
    canApproveVacation: false,
    canApproveWriteDowns: false,
    canAccessBilling: false,
    canAccessAccounting: false,
    canViewAuditLogs: false,
  },
];

/**
 * Matter catalog for assignment forms — derived from existing mock matters
 * (assigned + previously unassigned). Not a duplicate operational dataset.
 */
export const MOCK_MATTERS: AdminMatter[] = [
  {
    id: "mat-014",
    matterLabel: "Northwind Contract Dispute",
    matterReference: "MAT-2026-014",
    clientName: "Northwind Traders",
    practiceArea: "Litigation",
    status: "open",
    openedDate: "2026-05-10",
    engagementStatus: "signed",
    engagementDate: "2026-05-12",
    summary: "Commercial contract dispute requiring discovery responses before August deadline.",
    staffingUrgency: "high",
    responsibleAttorneyName: "Alex Rivera",
    responsibleEmployeeId: "emp-002",
    conflictWarning:
      "Opposing counsel previously engaged for related affiliate matter.",
  },
  {
    id: "mat-021",
    matterLabel: "Brightside Acquisition",
    matterReference: "MAT-2026-021",
    clientName: "Brightside Holdings",
    practiceArea: "Corporate",
    status: "open",
    openedDate: "2026-06-01",
    engagementStatus: "signed",
    engagementDate: "2026-06-03",
    summary: "M&A closing support and corporate filing coordination.",
    staffingUrgency: "high",
    responsibleAttorneyName: "Sam Okonkwo",
    responsibleEmployeeId: "emp-003",
  },
  {
    id: "mat-009",
    matterLabel: "Harbor Trust Review",
    matterReference: "MAT-2026-009",
    clientName: "Harbor Family Trust",
    practiceArea: "Trusts & Estates",
    status: "open",
    openedDate: "2026-07-15",
    engagementStatus: "signed",
    engagementDate: "2026-07-18",
    summary: "Trust instrument review and supervising partner coverage.",
    staffingUrgency: "medium",
    responsibleAttorneyName: "Jordan Hale",
    responsibleEmployeeId: "emp-001",
  },
  {
    id: "mat-031",
    matterLabel: "Summit Employment Claim",
    matterReference: "MAT-2026-031",
    clientName: "Summit Logistics",
    practiceArea: "Employment",
    status: "open",
    openedDate: "2026-04-20",
    engagementStatus: "signed",
    engagementDate: "2026-04-22",
    summary: "Employment claim response — internal due date already overdue.",
    staffingUrgency: "high",
    responsibleAttorneyName: "Taylor Nguyen",
    responsibleEmployeeId: "emp-007",
  },
  {
    id: "mat-027",
    matterLabel: "PixelSoft Patent Defense",
    matterReference: "MAT-2026-027",
    clientName: "PixelSoft Inc.",
    practiceArea: "Intellectual Property",
    status: "open",
    openedDate: "2026-06-18",
    engagementStatus: "signed",
    engagementDate: "2026-06-20",
    summary: "Patent defense claim construction and expert coordination.",
    staffingUrgency: "medium",
    responsibleAttorneyName: "Jamie Patel",
    responsibleEmployeeId: "emp-008",
  },
  {
    id: "mat-018",
    matterLabel: "Lakeside Closing",
    matterReference: "MAT-2026-018",
    clientName: "Lakeside Properties",
    practiceArea: "Trusts & Estates",
    status: "open",
    openedDate: "2026-06-28",
    engagementStatus: "signed",
    engagementDate: "2026-07-01",
    summary: "Real estate / estates closing package; legacy of-counsel coverage still open.",
    staffingUrgency: "medium",
    responsibleAttorneyName: "Reese Coleman",
    responsibleEmployeeId: "emp-013",
  },
  {
    id: "mat-011",
    matterLabel: "Vertex Class Action",
    matterReference: "MAT-2026-011",
    clientName: "Vertex Retail Group",
    practiceArea: "Litigation",
    status: "open",
    openedDate: "2026-03-05",
    engagementStatus: "signed",
    engagementDate: "2026-03-08",
    summary: "Class certification strategy oversight for retail defendant.",
    staffingUrgency: "high",
    responsibleAttorneyName: "Quinn Morales",
    responsibleEmployeeId: "emp-010",
  },
  {
    id: "mat-040",
    matterLabel: "Cedar Grove Zoning Appeal",
    matterReference: "MAT-2026-040",
    clientName: "Cedar Grove LLC",
    practiceArea: "Real Estate",
    status: "open",
    openedDate: "2026-07-30",
    engagementStatus: "pending",
    summary: "Zoning appeal — needs primary staffing (currently unassigned).",
    staffingUrgency: "high",
  },
  {
    id: "mat-041",
    matterLabel: "NovaTech License Audit",
    matterReference: "MAT-2026-041",
    clientName: "NovaTech Systems",
    practiceArea: "Intellectual Property",
    status: "open",
    openedDate: "2026-08-01",
    engagementStatus: "pending",
    summary: "Software license audit engagement awaiting attorney assignment.",
    staffingUrgency: "medium",
  },
  {
    id: "mat-042",
    matterLabel: "Beacon Nonprofit Formation",
    matterReference: "MAT-2026-042",
    clientName: "Beacon Community Fund",
    practiceArea: "Corporate",
    status: "closed",
    openedDate: "2026-05-01",
    engagementStatus: "signed",
    engagementDate: "2026-05-03",
    summary: "Nonprofit formation completed; closure documentation in progress.",
    staffingUrgency: "low",
    responsibleAttorneyName: "Sam Okonkwo",
    responsibleEmployeeId: "emp-003",
  },
  {
    id: "mat-099",
    matterLabel: "Legacy Archive File",
    matterReference: "MAT-2025-099",
    clientName: "Archive Client",
    practiceArea: "Firm Management",
    status: "archived",
    openedDate: "2024-11-01",
    engagementStatus: "expired",
    engagementDate: "2024-11-15",
    summary: "Archived legacy file retained for records retrieval only.",
    staffingUrgency: "low",
  },
];

/**
 * Assignment mock rows are display-only.
 * Future wiring should use existing matter_assignments (+ matters/profiles).
 */
export const MOCK_ASSIGNMENTS: AdminAssignment[] = [
  {
    id: "asg-001",
    matterId: "mat-014",
    matterLabel: "Northwind Contract Dispute",
    matterReference: "MAT-2026-014",
    clientName: "Northwind Traders",
    attorneyName: "Alex Rivera",
    employeeId: "emp-002",
    roleOnMatter: "Lead Counsel",
    practiceArea: "Litigation",
    priority: "high",
    status: "active",
    assignedDate: "2026-05-12",
    startDate: "2026-05-15",
    dueDate: "2026-08-08",
    /** Open estimated load for Alex — drives Over Capacity on Workload Board. */
    estimatedHours: 176,
    actualHours: 168,
    managerInstructions: "Prepare discovery responses before August deadline.",
    matterStatus: "open"
  },
  {
    id: "asg-002",
    matterId: "mat-021",
    matterLabel: "Brightside Acquisition",
    matterReference: "MAT-2026-021",
    clientName: "Brightside Holdings",
    attorneyName: "Sam Okonkwo",
    employeeId: "emp-003",
    roleOnMatter: "Deal Counsel",
    practiceArea: "Corporate",
    priority: "urgent",
    status: "active",
    assignedDate: "2026-06-03",
    startDate: "2026-06-05",
    dueDate: "2026-08-10",
    /** Near capacity demo: 142 / 150 weekly hours. */
    estimatedHours: 142,
    actualHours: 138,
    managerInstructions: "Coordinate closing checklist with corporate team.",
    matterStatus: "open"
  },
  {
    id: "asg-003",
    matterId: "mat-009",
    matterLabel: "Harbor Trust Review",
    matterReference: "MAT-2026-009",
    clientName: "Harbor Family Trust",
    attorneyName: "Jordan Hale",
    employeeId: "emp-001",
    roleOnMatter: "Supervising Partner",
    practiceArea: "Trusts & Estates",
    priority: "medium",
    status: "pending",
    assignedDate: "2026-07-18",
    startDate: "2026-07-20",
    dueDate: "2026-08-06",
    estimatedHours: 12,
    actualHours: 4,
    managerInstructions: "Review associate draft before client meeting.",
    matterStatus: "open"
  },
  {
    id: "asg-004",
    matterId: "mat-031",
    matterLabel: "Summit Employment Claim",
    matterReference: "MAT-2026-031",
    clientName: "Summit Logistics",
    attorneyName: "Taylor Nguyen",
    employeeId: "emp-007",
    roleOnMatter: "Lead Counsel",
    practiceArea: "Employment",
    priority: "high",
    status: "overdue",
    assignedDate: "2026-04-22",
    startDate: "2026-04-25",
    dueDate: "2026-07-28",
    estimatedHours: 30,
    actualHours: 31,
    managerInstructions: "File response; matter is past internal due date.",
    matterStatus: "open"
  },
  {
    id: "asg-005",
    matterId: "mat-027",
    matterLabel: "PixelSoft Patent Defense",
    matterReference: "MAT-2026-027",
    clientName: "PixelSoft Inc.",
    attorneyName: "Jamie Patel",
    employeeId: "emp-008",
    roleOnMatter: "IP Counsel",
    practiceArea: "Intellectual Property",
    priority: "medium",
    status: "active",
    assignedDate: "2026-06-20",
    startDate: "2026-06-22",
    dueDate: "2026-08-09",
    estimatedHours: 25,
    actualHours: 18,
    managerInstructions: "Draft claim construction outline.",
    matterStatus: "open"
  },
  {
    id: "asg-006",
    matterId: "mat-018",
    matterLabel: "Lakeside Closing",
    matterReference: "MAT-2026-018",
    clientName: "Lakeside Properties",
    attorneyName: "Reese Coleman",
    employeeId: "emp-013",
    roleOnMatter: "Lead Counsel",
    practiceArea: "Trusts & Estates",
    priority: "low",
    status: "completed",
    assignedDate: "2026-07-01",
    startDate: "2026-07-02",
    dueDate: "2026-09-15",
    estimatedHours: 20,
    actualHours: 19,
    managerInstructions: "Closing package completed.",
    matterStatus: "open",
    completedDate: "2026-08-01"
  },
  {
    id: "asg-007",
    matterId: "mat-011",
    matterLabel: "Vertex Class Action",
    matterReference: "MAT-2026-011",
    clientName: "Vertex Retail Group",
    attorneyName: "Quinn Morales",
    employeeId: "emp-010",
    roleOnMatter: "Partner",
    practiceArea: "Litigation",
    priority: "high",
    status: "active",
    assignedDate: "2026-03-08",
    startDate: "2026-03-10",
    dueDate: "2026-08-20",
    estimatedHours: 45,
    actualHours: 33,
    managerInstructions: "Oversee class certification strategy.",
    matterStatus: "open"
  },
  {
    id: "asg-008",
    matterId: "mat-014",
    matterLabel: "Northwind Contract Dispute",
    matterReference: "MAT-2026-014",
    clientName: "Northwind Traders",
    attorneyName: "Riley Chen",
    employeeId: "emp-004",
    roleOnMatter: "Litigation Paralegal",
    practiceArea: "Litigation",
    priority: "medium",
    status: "active",
    assignedDate: "2026-06-01",
    startDate: "2026-06-02",
    dueDate: "2026-08-12",
    /** Balanced demo: 120 / 160 = 75%. */
    estimatedHours: 120,
    actualHours: 118,
    managerInstructions: "Maintain exhibit binders and deposition indexes.",
    matterStatus: "open",
  },
  {
    id: "asg-009",
    matterId: "mat-009",
    matterLabel: "Harbor Trust Review",
    matterReference: "MAT-2026-009",
    clientName: "Harbor Family Trust",
    attorneyName: "Casey Brooks",
    employeeId: "emp-005",
    roleOnMatter: "Admin Support",
    practiceArea: "Administration",
    priority: "low",
    status: "active",
    assignedDate: "2026-07-20",
    startDate: "2026-07-21",
    dueDate: "2026-08-12",
    estimatedHours: 8,
    actualHours: 2,
    managerInstructions: "Coordinate trust packet logistics while on leave coverage.",
    matterStatus: "open",
  },
  {
    id: "asg-010",
    matterId: "mat-018",
    matterLabel: "Lakeside Closing",
    matterReference: "MAT-2026-018",
    clientName: "Lakeside Properties",
    attorneyName: "Morgan Ellis",
    employeeId: "emp-006",
    roleOnMatter: "Of Counsel",
    practiceArea: "Real Estate",
    priority: "medium",
    status: "active",
    assignedDate: "2026-05-01",
    startDate: "2026-05-02",
    dueDate: "2026-08-15",
    estimatedHours: 10,
    actualHours: 4,
    managerInstructions: "Legacy assignment still open after inactivation.",
    matterStatus: "open",
  },
  {
    id: "asg-011",
    matterId: "mat-040",
    matterLabel: "Cedar Grove Zoning Appeal",
    matterReference: "MAT-2026-040",
    clientName: "Cedar Grove LLC",
    attorneyName: "Drew Santos",
    employeeId: "emp-011",
    roleOnMatter: "Associate",
    practiceArea: "Real Estate",
    priority: "low",
    status: "active",
    assignedDate: "2026-07-25",
    startDate: "2026-07-26",
    dueDate: "2026-09-01",
    /** Available demo: 64 / 160 = 40%. */
    estimatedHours: 64,
    actualHours: 40,
    managerInstructions: "Draft zoning appeal outline.",
    matterStatus: "open",
  },
];

export const MOCK_UNASSIGNED_MATTERS: AdminUnassignedMatter[] = [
  {
    id: "umat-001",
    matterLabel: "Cedar Grove Zoning Appeal",
    matterReference: "MAT-2026-040",
    practiceArea: "Real Estate",
    openedDate: "2026-07-30",
    urgency: "high",
  },
  {
    id: "umat-002",
    matterLabel: "NovaTech License Audit",
    matterReference: "MAT-2026-041",
    practiceArea: "Intellectual Property",
    openedDate: "2026-08-01",
    urgency: "medium",
  },
  {
    id: "umat-003",
    matterLabel: "Beacon Nonprofit Formation",
    matterReference: "MAT-2026-042",
    practiceArea: "Corporate",
    openedDate: "2026-08-02",
    urgency: "low",
  },
];

export const MOCK_APPROVALS: AdminApproval[] = [
  {
    id: "apr-001",
    title: "URGENT: 18.0 hrs — Northwind discovery",
    type: "time_entry",
    submittedBy: "Alex Rivera",
    employeeId: "emp-002",
    summary: "URGENT: 18.0 hrs client deadline — Northwind discovery",
    status: "pending",
    priority: "urgent",
    submittedAt: "2026-08-03T08:15:00Z",
    amountOrHours: "18.0 hrs",
    matterId: "mat-014",
    matterLabel: "Northwind Contract Dispute",
    matterReference: "MAT-2026-014",
    matterStatus: "open",
    assignedApproverId: "emp-001",
    assignedApproverName: "Jordan Hale",
    originalSnapshot: "time_entry|18h|Northwind|2026-08-02",
    timeEntryDate: "2026-08-02",
    timeEntryHours: 18,
    timeEntryBillable: true,
    timeEntryDescription: "Discovery responses and exhibit preparation under client deadline.",
  },
  {
    id: "apr-002",
    title: "Courier and filing fees — Brightside",
    type: "expense",
    submittedBy: "Sam Okonkwo",
    employeeId: "emp-003",
    summary: "Courier and filing fees — Brightside closing",
    status: "pending",
    priority: "normal",
    submittedAt: "2026-08-02T11:05:00Z",
    amountOrHours: "$286.40",
    matterId: "mat-021",
    matterLabel: "Brightside Acquisition",
    matterReference: "MAT-2026-021",
    matterStatus: "open",
    assignedApproverId: "emp-001",
    assignedApproverName: "Jordan Hale",
    originalSnapshot: "expense|286.40|Brightside|courier",
    expenseAmount: 286.4,
    expenseCategory: "Filing & courier",
    expensePurpose: "Closing-day courier and secretary of state filing fees.",
    receiptStatus: "attached",
  },
  {
    id: "apr-003",
    title: "Vacation request — Aug 6–10 (deadline conflict)",
    type: "vacation",
    submittedBy: "Alex Rivera",
    employeeId: "emp-002",
    summary: "Vacation request — Aug 6–10 (deadline conflict)",
    status: "pending",
    priority: "urgent",
    submittedAt: "2026-07-29T09:40:00Z",
    amountOrHours: "5 days",
    matterId: "mat-014",
    matterLabel: "Northwind Contract Dispute",
    matterReference: "MAT-2026-014",
    matterStatus: "open",
    assignedApproverId: "emp-001",
    assignedApproverName: "Jordan Hale",
    originalSnapshot: "vacation|2026-08-06|2026-08-10|Alex",
    vacationStartDate: "2026-08-06",
    vacationEndDate: "2026-08-10",
    vacationWorkdays: 5,
    vacationComments: "Personal travel overlapping Northwind discovery deadline.",
    backupEmployeeId: undefined,
    backupEmployeeName: undefined,
  },
  {
    id: "apr-004",
    title: "Reassign Harbor Trust supervising role",
    type: "reassignment",
    submittedBy: "Casey Brooks",
    employeeId: "emp-005",
    summary: "Rebalance Harbor Trust staffing",
    status: "approved",
    priority: "normal",
    submittedAt: "2026-07-28T16:10:00Z",
    matterId: "mat-009",
    matterLabel: "Harbor Trust Review",
    matterReference: "MAT-2026-009",
    matterStatus: "open",
    assignedApproverId: "emp-001",
    assignedApproverName: "Jordan Hale",
    reviewerId: "emp-001",
    reviewerName: "Jordan Hale",
    reviewedAt: "2026-07-29T10:00:00Z",
    decision: "approved",
    reviewNotes: "Approved temporary supervising coverage.",
    originalSnapshot: "reassignment|Harbor Trust|approved",
    requestDetails: "Move day-to-day supervision while administrator is on leave.",
  },
  {
    id: "apr-005",
    title: "URGENT: Court filing overtime — Summit",
    type: "time_entry",
    submittedBy: "Taylor Nguyen",
    employeeId: "emp-007",
    summary: "URGENT: Court filing overtime — Summit claim",
    status: "pending",
    priority: "urgent",
    submittedAt: "2026-08-02T19:30:00Z",
    amountOrHours: "6.5 hrs",
    matterId: "mat-031",
    matterLabel: "Summit Employment Claim",
    matterReference: "MAT-2026-031",
    matterStatus: "open",
    assignedApproverId: "emp-001",
    assignedApproverName: "Jordan Hale",
    originalSnapshot: "time_entry|6.5h|Summit|2026-08-01",
    timeEntryDate: "2026-08-01",
    timeEntryHours: 6.5,
    timeEntryBillable: true,
    timeEntryDescription: "Emergency overtime for court filing package.",
  },
  {
    id: "apr-006",
    title: "Expert retainer — PixelSoft",
    type: "expense",
    submittedBy: "Jamie Patel",
    employeeId: "emp-008",
    summary: "Expert retainer — PixelSoft patent defense",
    status: "pending",
    priority: "normal",
    submittedAt: "2026-07-30T14:00:00Z",
    amountOrHours: "$2,500.00",
    matterId: "mat-027",
    matterLabel: "PixelSoft Patent Defense",
    matterReference: "MAT-2026-027",
    matterStatus: "open",
    assignedApproverId: "emp-001",
    assignedApproverName: "Jordan Hale",
    originalSnapshot: "expense|2500|PixelSoft|expert",
    expenseAmount: 2500,
    expenseCategory: "Expert / consultant",
    expensePurpose: "Retainer for technical expert on claim construction.",
    receiptStatus: "missing",
  },
  {
    id: "apr-007",
    title: "PTO — Sep 2–5",
    type: "vacation",
    submittedBy: "Drew Santos",
    employeeId: "emp-011",
    summary: "PTO — Sep 2–5",
    status: "pending",
    priority: "normal",
    submittedAt: "2026-08-03T12:45:00Z",
    amountOrHours: "4 days",
    assignedApproverId: "emp-003",
    assignedApproverName: "Sam Okonkwo",
    originalSnapshot: "vacation|2026-09-02|2026-09-05|Drew",
    vacationStartDate: "2026-09-02",
    vacationEndDate: "2026-09-05",
    vacationWorkdays: 4,
    vacationComments: "Short PTO; no open deadlines in window.",
    backupEmployeeId: "emp-003",
    backupEmployeeName: "Sam Okonkwo",
  },
  {
    id: "apr-008",
    title: "Write-down request — Vertex research",
    type: "write_down",
    submittedBy: "Quinn Morales",
    employeeId: "emp-010",
    summary: "Write-down request — Vertex research",
    status: "pending",
    priority: "normal",
    submittedAt: "2026-07-25T15:00:00Z",
    amountOrHours: "$1,200.00",
    matterId: "mat-011",
    matterLabel: "Vertex Class Action",
    matterReference: "MAT-2026-011",
    matterStatus: "open",
    assignedApproverId: "emp-001",
    assignedApproverName: "Jordan Hale",
    originalSnapshot: "write_down|1200|Vertex",
    requestDetails: "Write down non-billable research time incurred during strategy reset.",
  },
  {
    id: "apr-009",
    title: "Additional work authorization — Cedar Grove",
    type: "additional_work",
    submittedBy: "Jamie Patel",
    employeeId: "emp-008",
    summary: "Additional work authorization — Cedar Grove",
    status: "pending",
    priority: "normal",
    submittedAt: "2026-08-01T08:00:00Z",
    amountOrHours: "15.0 hrs",
    matterId: "mat-040",
    matterLabel: "Cedar Grove Zoning Appeal",
    matterReference: "MAT-2026-040",
    matterStatus: "open",
    assignedApproverId: "emp-001",
    assignedApproverName: "Jordan Hale",
    originalSnapshot: "additional_work|15h|Cedar Grove",
    requestDetails: "Authorize 15 additional hours for zoning brief support.",
  },
  {
    id: "apr-010",
    title: "Matter closure request — Beacon Nonprofit",
    type: "matter_closure",
    submittedBy: "Sam Okonkwo",
    employeeId: "emp-003",
    summary: "Matter closure request — Beacon Nonprofit",
    status: "returned",
    priority: "normal",
    submittedAt: "2026-07-20T11:00:00Z",
    matterId: "mat-042",
    matterLabel: "Beacon Nonprofit Formation",
    matterReference: "MAT-2026-042",
    matterStatus: "closed",
    assignedApproverId: "emp-001",
    assignedApproverName: "Jordan Hale",
    reviewerId: "emp-001",
    reviewerName: "Jordan Hale",
    reviewedAt: "2026-07-22T09:30:00Z",
    decision: "returned",
    reviewNotes: "Return: attach final formation documents before closure.",
    originalSnapshot: "matter_closure|Beacon|returned",
    requestDetails: "Close completed nonprofit formation engagement.",
  },
  {
    id: "apr-011",
    title: "Time on archived matter — Legacy Archive",
    type: "time_entry",
    submittedBy: "Alex Rivera",
    employeeId: "emp-002",
    summary: "Time on archived matter — Legacy Archive",
    status: "pending",
    priority: "normal",
    submittedAt: "2026-08-04T07:00:00Z",
    amountOrHours: "2.0 hrs",
    matterId: "mat-099",
    matterLabel: "Legacy Archive File",
    matterReference: "MAT-2025-099",
    matterStatus: "archived",
    assignedApproverId: "emp-001",
    assignedApproverName: "Jordan Hale",
    originalSnapshot: "time_entry|2h|archived|legacy",
    timeEntryDate: "2026-08-03",
    timeEntryHours: 2,
    timeEntryBillable: false,
    timeEntryDescription: "File retrieval notes on archived matter.",
  },
  {
    id: "apr-012",
    title: "Invalid hours time entry — Harbor Trust",
    type: "time_entry",
    submittedBy: "Taylor Nguyen",
    employeeId: "emp-007",
    summary: "Invalid hours time entry — Harbor Trust",
    status: "pending",
    priority: "normal",
    submittedAt: "2026-08-04T09:00:00Z",
    amountOrHours: "0.0 hrs",
    matterId: "mat-009",
    matterLabel: "Harbor Trust Review",
    matterReference: "MAT-2026-009",
    matterStatus: "open",
    assignedApproverId: "emp-001",
    assignedApproverName: "Jordan Hale",
    originalSnapshot: "time_entry|0h|Harbor Trust|invalid",
    timeEntryDate: "2026-08-04",
    timeEntryHours: 0,
    timeEntryBillable: true,
    timeEntryDescription: "Drafting notes — hours left at zero by mistake.",
  },
];

export const MOCK_VACATIONS: AdminVacation[] = [
  {
    id: "vac-001",
    employeeId: "emp-005",
    employeeName: "Casey Brooks",
    practiceArea: "Administration",
    startDate: "2026-07-28",
    endDate: "2026-08-15",
    status: "approved",
    days: 14,
  },
  {
    id: "vac-002",
    employeeId: "emp-010",
    employeeName: "Quinn Morales",
    practiceArea: "Litigation",
    startDate: "2026-08-18",
    endDate: "2026-08-22",
    status: "approved",
    days: 5,
  },
  {
    id: "vac-003",
    employeeId: "emp-013",
    employeeName: "Reese Coleman",
    practiceArea: "Trusts & Estates",
    startDate: "2026-09-01",
    endDate: "2026-09-05",
    status: "approved",
    days: 5,
  },
  {
    id: "vac-004",
    employeeId: "emp-008",
    employeeName: "Jamie Patel",
    practiceArea: "Intellectual Property",
    startDate: "2026-08-25",
    endDate: "2026-08-27",
    status: "approved",
    days: 3,
  },
];

const OPEN_MATTERS: Record<string, number> = {
  "emp-001": 2,
  "emp-002": 8,
  "emp-003": 5,
  "emp-007": 4,
  "emp-008": 3,
  "emp-010": 3,
  "emp-011": 2,
  "emp-013": 3,
};

const PENDING_BY_EMP: Record<string, number> = {
  "emp-002": 1,
  "emp-003": 1,
  "emp-007": 1,
  "emp-008": 1,
};

const MATTERS_CLOSED: Record<string, number> = {
  "emp-001": 1,
  "emp-002": 3,
  "emp-003": 2,
  "emp-007": 2,
  "emp-008": 1,
  "emp-010": 2,
  "emp-011": 0,
  "emp-013": 1,
};

export const MOCK_WORKLOAD = buildWorkloadItems(
  MOCK_EMPLOYEES,
  OPEN_MATTERS,
  PENDING_BY_EMP,
);

export const MOCK_PRODUCTIVITY = buildProductivityMetrics(
  MOCK_EMPLOYEES,
  MATTERS_CLOSED,
);

export const MOCK_DASHBOARD_SUMMARY = buildDashboardSummary({
  employees: MOCK_EMPLOYEES,
  approvals: MOCK_APPROVALS,
  assignments: MOCK_ASSIGNMENTS,
  unassignedMatters: MOCK_UNASSIGNED_MATTERS,
  referenceDate: ADMIN_REFERENCE_DATE,
});

/** Toggle helpers for empty/error UI patterns during development */
export const ADMIN_UI_FLAGS = {
  forceEmpty: false,
  forceError: false,
  forceLoading: false,
} as const;

/** Snapshot helper used by Refresh on the Manager Dashboard */
export function getAdminDashboardDataset() {
  return {
    referenceDate: ADMIN_REFERENCE_DATE,
    employees: MOCK_EMPLOYEES,
    attorneys: MOCK_ATTORNEYS,
    assignments: MOCK_ASSIGNMENTS,
    unassignedMatters: MOCK_UNASSIGNED_MATTERS,
    approvals: MOCK_APPROVALS,
    vacations: MOCK_VACATIONS,
    jobApplications: MOCK_JOB_APPLICATIONS,
    workload: buildWorkloadItems(MOCK_EMPLOYEES, OPEN_MATTERS, PENDING_BY_EMP),
    productivity: buildProductivityMetrics(MOCK_EMPLOYEES, MATTERS_CLOSED),
    summary: buildDashboardSummary({
      employees: MOCK_EMPLOYEES,
      approvals: MOCK_APPROVALS,
      assignments: MOCK_ASSIGNMENTS,
      unassignedMatters: MOCK_UNASSIGNED_MATTERS,
      referenceDate: ADMIN_REFERENCE_DATE,
    }),
  };
}
